### PR TITLE
Add Strong Name signing

### PR DESCRIPTION
**Pull request by yitzhaks**
In order to to use TDigest from a strongly named application, add Strong Name signing to the main assembly. Since this isn't a security feature, create an snk with no password just for self declared identification.

### CODE REVIEW

**Review by quantumtunneling — APPROVED** [review]
Thanks for the PR

**Comment by yitzhaks** [comment]
Thanks for approving it so fast!
Can you please publish version 1.0.7 to NuGet with this change?

**Comment by yitzhaks** [comment]
@quantumtunneling?

**Comment by quantumtunneling** [comment]
Hey, I created a new 1.07 release. Sorry for delay, been super busy at work!
________________________________

**Comment by yitzhaks** [comment]
Thanks @quantumtunneling so much, and no worries, I was just afraid you didn't get a notification about my comment. Can you please publish it to NuGet.org too? Our build system strongly prefers binary drops from NuGet.

**Comment by yitzhaks** [comment]
@quantumtunneling, I'm really sorry to nag, but can you please help us? This is blocking our adoption of TDigest.

**Comment by quantumtunneling** [comment]
Hey I'll see if I can get this updated this evening. I'll Keep you posted thanks
________________________________

**Comment by yitzhaks** [comment]
Thanks a lot!

**Comment by quantumtunneling** [comment]
Give this a try and let me know if anything isn't working. I had to rebuild the package with .NET Standard.

https://www.nuget.org/packages/TDigest.NET/1.0.7
________________________________

**Comment by yitzhaks** [comment]
Thanks Graham! We're having difficulty consuming the netstandard DLL from out .NET Framework project. Is there any chance you can publish a NuGet package targeting both?

**Comment by quantumtunneling** [comment]
What version of .NET are you using? I only tested it with 4.6. I'll put out a framework version tonight.
________________________________

**Comment by quantumtunneling** [comment]
okay, give this one a shot. I de-listed the other one.

Install-Package TDigest -Version 1.0.7
________________________________

**Comment by yitzhaks** [comment]
Thanks Graham! We'll take it for a spin first thing next week.

**Pull request merged**
